### PR TITLE
support geojson

### PR DESCRIPTION
**Pull request by junosuarez**
for example

### CODE REVIEW

**Comment by junosuarez** [comment]
related to #2 

here's an example of the output in a gist: https://gist.github.com/jden/9b848fce9d72530b7a89

**Comment by junosuarez** [comment]
note, there's some hackish filtering for items which fail geocoding, since i was getting some weird data with cross streets that weren't generating a lat long

**Comment by phated** [comment]
Woot!  Same with us

**Comment by phated** [comment]
Added popups back in https://github.com/phated/phoenix-dispatch/commit/700830bc4bb29916d692d701938377501de22872

**Pull request merged**
